# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcc-4.9
    - g++-4.9
    #- valgrind
os:
  - linux
language: cpp

install:
  #from: https://github.com/boostorg/hana/blob/master/.travis.yml
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version
  
compiler:
  - gcc
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build || true
  - cd build/
  - cmake -DBUILD_EXAMPLES=ON -DBUILD_TESTS=OFF -DGOOGLE_TEST_BUILD_DIR="" -DGOOGLE_TEST_INCLUDE_DIR="" ..  
  - make
notifications:
  email: false
sudo: false
